#!/usr/bin/env python3
import sys
import subprocess
import os

src_dir = '/home/odoo/src'

command = [f'{src_dir}/odoo/odoo-bin']
odoo_bin_args = sys.argv[1:]
for arg in ['--internal', '--vscode', '--new', '--upgrade', '--community']:
  if arg in odoo_bin_args:
    odoo_bin_args.remove(arg)

if odoo_bin_args:
  command += odoo_bin_args

if '-d' in sys.argv:
  dbname = sys.argv[sys.argv.index('-d') + 1]
else:
  # We are likely never going to checkout to a random commit on design-themes but always on the branch
  os.chdir(f'{src_dir}/design-themes')
  current_branch = subprocess.check_output(['git', 'branch', '--show-current']).decode("utf-8").strip()

  if current_branch.startswith('saas'):
    dbname = f'db-{current_branch[5:]}'
  else:
    dbname = f'db-{current_branch}'
  command += ['-d', dbname]

os.chdir(f'{src_dir}/odoo')

addons_path = [f'{src_dir}/enterprise', f'{src_dir}/design-themes', f'{src_dir}/odoo/addons']
if '--community' in sys.argv:
    addons_path = [f'{src_dir}/odoo/addons']
if '--internal' in sys.argv:
  addons_path += [f'{src_dir}/internal/private', f'{src_dir}/internal/trial', f'{src_dir}/internal/demo', f'{src_dir}/internal/default']

command += [f'--addons-path={",".join(addons_path)}']

if '--upgrade' in sys.argv:
  upgrade_path = [f'{src_dir}/upgrade-util/src', f'{src_dir}/upgrade/migrations']
  command += [
    '--stop-after-init',
    f'--upgrade-path={",".join(upgrade_path)}',
    '-u all',
  ]

if '--vscode' in sys.argv:
  command = ['python3', '-m', 'debugpy', '--listen', 'localhost:5678'] + command

if '--new' in sys.argv:
  subprocess.call(['dropdb', dbname])

def print_complete_command():
  print(' '.join(command))

try:
  print_complete_command()
  print()
  subprocess.call(command)
except:
  pass
finally:
  print()
  print('Odoo terminated, command:')
  print_complete_command()
