#!/usr/bin/env python3
import sys
import subprocess
import os

os.chdir('/home/odoo/src/odoo')

current_branch = subprocess.check_output(['git', 'branch', '--show-current']).decode("utf-8").strip()
addons_path = ['/home/odoo/src/enterprise', '/home/odoo/src/design-themes', '/home/odoo/src/odoo/addons']
dbname = f'db-{current_branch}'

if '-i' in sys.argv:
  addons_path += ['/home/odoo/src/internal/private', '/home/odoo/src/internal/trial', '/home/odoo/src/internal/demo', '/home/odoo/src/internal/default']

command = ['/home/odoo/src/odoo/odoo-bin', f'--addons-path={",".join(addons_path)}', '-d', dbname]
if '-d' in sys.argv:
  command = ['python3', '-m', 'debugpy', '--listen', 'localhost:5678'] + command

if '-c' in sys.argv:
  subprocess.call(['dropdb', dbname])

try:
  subprocess.call(command)
except:
  print()
  print('Command:')
  print(' '.join(command))